spring:
  cloud:
    nacos:
      # Nacos 作为注册中心的配置项，对应 NacosDiscoveryProperties 配置类
      discovery:
        server-addr: 47.102.124.178:8848 # Nacos 服务器地址
        namespace: b4223595-12ff-4126-a619-7e168d4e0c6e  # Nacos 命名空间 uat 的编号
