spring:
  cloud:
    nacos:
      # Nacos 作为注册中心的配置项，对应 NacosDiscoveryProperties 配置类
      discovery:
        server-addr: 47.102.124.178:8848 # Nacos 服务器地址
        namespace: f4438861-9853-4028-8c5e-70fc2b7e6993 # Nacos 命名空间 dev 的编号
